name=Zabbix Monitor
id=zabbix_monitor
author=ID22
version=1.0.1
description=Sends DirectAdmin events to Zabbix via zabbix_sender
download_url=https://github.com/petervansark/zabbixdaplugin/releases/latest/download/zabbix_monitor.tar.gz
version_url=https://raw.githubusercontent.com/petervansark/zabbixdaplugin/main/plugin.conf
